### ISSUE TITLE
[Bug] Uneven Side padding in Grid view for sub sections

### ISSUE THREAD

**Issue by Mathew20kdroid** [rebelonion/Dantotsu#396]
for the **expanded list** in all **Manga/Home/Anime** tabs , all the **subsections when expanded** have the **side paddings uneven in grid view,** for the list view its fine........

![WhatsApp Image 2024-05-21 at 19 43 38_99345e2a](https://github.com/rebelonion/Dantotsu/assets/71634955/b99cd08d-3980-47b5-97d3-47f61246d7f5)

**Comment by Mathew20kdroid** [comment]
it the opposite side that's uneven now

**Comment by VitaToolArchive** [comment]
Anime Downloader crashes dantotsu

**Comment by VitaToolArchive** [comment]
Date/time: Wed May 22 10:29:40 GMT+08:00 2024
Device: 21081111RG
OS version: 14
App version: 3.0.0-beta04
App version code: 300000000
SDK version: 34
Manufacturer: Xiaomi
Brand: Xiaomi
Product: amber_global
Device: amber
Hardware: mt6893
Host: pangu-build-component-system-64756-mlm50-glnw9-d8g43
ID: UP1A.231005.007
Type: user
User: builder
Tags: release-keys
Time: 1710432372000
Radio: MOLY.NR15.R3.TC8.PR2.SP.V2.1.P95,MOLY.NR15.R3.TC8.PR2.SP.V2.1.P95
Bootloader: unknown
Board: amber
Fingerprint: Xiaomi/amber_global/amber:14/UP1A.231005.007/V816.0.4.0.UKWMIXM:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: main
Exception: Extension is not a DownloadAddonApi
Stack trace:
java.lang.IllegalStateException: Extension is not a DownloadAddonApi
	at ani.dantotsu.addons.AddonLoader$Companion.loadExtension(AddonLoader.kt:105)
	at ani.dantotsu.addons.AddonLoader$Companion.loadFromPkgName(AddonLoader.kt:129)
	at ani.dantotsu.addons.AddonInstallReceiver$onReceive$2.invokeSuspend(AddonInstallReceiver.kt:84)
	at ani.dantotsu.addons.AddonInstallReceiver$onReceive$2.invoke(Unknown Source:8)
	at ani.dantotsu.addons.AddonInstallReceiver$onReceive$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at tachiyomi.core.util.lang.CoroutinesExtensionsKt.launchNow(CoroutinesExtensions.kt:44)
	at ani.dantotsu.addons.AddonInstallReceiver.onReceive(AddonInstallReceiver.kt:78)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1866)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$gDuJqgxY6Zb-ifyeubKeivTLAwk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9be313d, Dispatchers.Main]
