### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by jzrxl** [rebelonion/Dantotsu#399]
The new update causes the app to crash when downloading anime.

Date/time: Fri May 24 17:23:22 GMT+08:00 2024
Device: TECNO BG6
OS version: 13
App version: 3.1.0
App version code: 300100000
SDK version: 33
Manufacturer: TECNO
Brand: TECNO
Product: BG6-OP
Device: TECNO-BG6
Hardware: BG6
Host: build-1-13
ID: TP1A.220624.014
Type: user
User: buildsrv-ci
Tags: release-keys
Time: 1713359864000
Bootloader: unknown
Board: TECNO-BG6
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: DefaultDispatcher-worker-3
Activity: MediaDetailsActivity
Exception: abstract method "kotlin.Pair ani.dantotsu.addons.download.DownloadAddonApiV2.getFileExtension()"
Stack trace:
java.lang.AbstractMethodError: abstract method "kotlin.Pair ani.dantotsu.addons.download.DownloadAddonApiV2.getFileExtension()"
	at ani.dantotsu.download.anime.AnimeDownloaderService$download$2.invokeSuspend(AnimeDownloaderService.kt:228)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8194)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@71bc408, Dispatchers.Default]

**Comment by rebelonion** [comment]
Thx for the report. Seems like your download addon isn't up to date. But that still shouldn't cause a crash so I'll look into that part
