### ISSUE TITLE
App Died When Trying to Cast Error 

### ISSUE THREAD

**Issue by 9SYorhaDestroyer** [rebelonion/Dantotsu#450]
Hello once again creator of Dantotsu I seem to have encountered an error when I accidentally hit the cast button on the video player when we watching bleached as your blood War season 1 English dub when I accidentally hit the cast apparently this error popped up saying app has died and as such even though it was an accident I tried it again and it's showing me the same error now I don't know what has happened to cause this but this was purely by accident that I discovered this book so in the next future update could you please look into it I'm also sending you a screenshot I took of it as well as of course the file and text of it as well please look into it at your earliest convenience thank youDate/time: Tue Jul 02 11:28:14 MST 2024
Device: SM-A156U
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: samsung
Brand: samsung
Product: a15xsq
Device: a15x
Hardware: mt6835
Host: 21DK7902
ID: UP1A.231005.007
Type: user
User: dpi
Tags: release-keys
Time: 1716425917000
Radio: A156USQS2BXE5
Bootloader: A156USQS2BXE5
Board: a15x
Fingerprint: samsung/a15xsq/a15x:14/UP1A.231005.007/A156USQS2BXE5:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: main
Activity: ExoplayerView
Exception: null
Stack trace:
java.lang.NullPointerException
	at ani.dantotsu.media.anime.ExoplayerView.cast(ExoplayerView.kt:2126)
	at ani.dantotsu.media.anime.ExoplayerView.access$cast(ExoplayerView.kt:178)
	at ani.dantotsu.media.anime.ExoplayerView$onCreate$31$1.invoke(ExoplayerView.kt:1215)
	at ani.dantotsu.media.anime.ExoplayerView$onCreate$31$1.invoke(ExoplayerView.kt:1215)
	at ani.dantotsu.media.anime.CustomCastButton.performClick(ExoplayerView.kt:2322)
	at android.view.View.performClickInternal(View.java:8024)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31890)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Date/time: Tue Jul 02 11:26:37 MST 2024
Device: SM-A156U
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: samsung
Brand: samsung
Product: a15xsq
Device: a15x
Hardware: mt6835
Host: 21DK7902
ID: UP1A.231005.007
Type: user
User: dpi
Tags: release-keys
Time: 1716425917000
Radio: A156USQS2BXE5
Bootloader: A156USQS2BXE5
Board: a15x
Fingerprint: samsung/a15xsq/a15x:14/UP1A.231005.007/A156USQS2BXE5:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: main
Activity: ExoplayerView
Exception: null
Stack trace:
java.lang.NullPointerException
	at ani.dantotsu.media.anime.ExoplayerView.cast(ExoplayerView.kt:2126)
	at ani.dantotsu.media.anime.ExoplayerView.access$cast(ExoplayerView.kt:178)
	at ani.dantotsu.media.anime.ExoplayerView$onCreate$31$1.invoke(ExoplayerView.kt:1215)
	at ani.dantotsu.media.anime.ExoplayerView$onCreate$31$1.invoke(ExoplayerView.kt:1215)
	at ani.dantotsu.media.anime.CustomCastButton.performClick(ExoplayerView.kt:2322)
	at android.view.View.performClickInternal(View.java:8024)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31890)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Date/time: Tue Jul 02 11:26:37 MST 2024
Device: SM-A156U
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: samsung
Brand: samsung
Product: a15xsq
Device: a15x
Hardware: mt6835
Host: 21DK7902
ID: UP1A.231005.007
Type: user
User: dpi
Tags: release-keys
Time: 1716425917000
Radio: A156USQS2BXE5
Bootloader: A156USQS2BXE5
Board: a15x
Fingerprint: samsung/a15xsq/a15x:14/UP1A.231005.007/A156USQS2BXE5:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: main
Activity: ExoplayerView
Exception: null
Stack trace:
java.lang.NullPointerException
	at ani.dantotsu.media.anime.ExoplayerView.cast(ExoplayerView.kt:2126)
	at ani.dantotsu.media.anime.ExoplayerView.access$cast(ExoplayerView.kt:178)
	at ani.dantotsu.media.anime.ExoplayerView$onCreate$31$1.invoke(ExoplayerView.kt:1215)
	at ani.dantotsu.media.anime.ExoplayerView$onCreate$31$1.invoke(ExoplayerView.kt:1215)
	at ani.dantotsu.media.anime.CustomCastButton.performClick(ExoplayerView.kt:2322)
	at android.view.View.performClickInternal(View.java:8024)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31890)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
![Screenshot_20240702_113039_Dantotsu](https://github.com/rebelonion/Dantotsu/assets/136257130/9922ef2d-99b9-4202-bb8b-d39966fce86c)

**Comment by rebelonion** [comment]
closing as duplicate
