### ISSUE TITLE
App died(crash)

### ISSUE THREAD

**Issue by Unknowmperson** [rebelonion/Dantotsu#459]
Date/time: Wed Jul 24 12:00:12 GMT+03:00 2024
Device: M2102J20SI
OS version: 12
App version: 3.1.0
App version code: 300100000
SDK version: 31
Manufacturer: Xiaomi
Brand: POCO
Product: bhima_in
Device: bhima
Hardware: qcom
Host: c4-miui-ota-bd131.bj
ID: SKQ1.211006.001
Type: user
User: builder
Tags: release-keys
Time: 1646922465000
Radio: 1.0.c3-00161-0310_2101_6c868d9,1.0.c3-00161-0310_2101_6c868d9
Bootloader: unknown
Board: bhima
Fingerprint: POCO/bhima_in/bhima:12/SKQ1.211006.001/V13.0.1.0.SJUINXM:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: main
Activity: MediaDetailsActivity
Exception: Binary XML file line #41 in ani.dantotsu:layout/item_title_trailer: Binary XML file line #41 in ani.dantotsu:layout/item_title_trailer: Error inflating class android.webkit.WebView
Stack trace:
android.view.InflateException: Binary XML file line #41 in ani.dantotsu:layout/item_title_trailer: Binary XML file line #41 in ani.dantotsu:layout/item_title_trailer: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #41 in ani.dantotsu:layout/item_title_trailer: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:881)
	at android.view.LayoutInflater.createView(LayoutInflater.java:803)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:957)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:977)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1031)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:988)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1150)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1111)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1153)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1111)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1153)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1111)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:709)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:547)
	at ani.dantotsu.databinding.ItemTitleTrailerBinding.inflate(ItemTitleTrailerBinding.java:55)
	at ani.dantotsu.media.MediaInfoFragment$onViewCreated$3.invoke(MediaInfoFragment.kt:329)
	at ani.dantotsu.media.MediaInfoFragment$onViewCreated$3.invoke(MediaInfoFragment.kt:94)
	at ani.dantotsu.media.MediaInfoFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process ani.dantotsu (pid 18269), lock owner ani.dantotsu:error_process (pid 16237)
	at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:201)
	at org.chromium.android_webview.AwBrowserProcess.j(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:16)
	at com.android.webview.chromium.M.e(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:203)
	at com.android.webview.chromium.M.b(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:42)
	at com.android.webview.chromium.M.g(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:5)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.l(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:8)
	at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle6432.aab-stable-647813433:97)
	at android.webkit.WebView.<init>(WebView.java:443)
	at android.webkit.WebView.<init>(WebView.java:363)
	at android.webkit.WebView.<init>(WebView.java:345)
	at android.webkit.WebView.<init>(WebView.java:332)
	... 34 more

**Comment by rebelonion** [comment]
Hopefully better in 3.2.0+
