### ISSUE TITLE
App Died - Crash Report

### ISSUE THREAD

**Issue by mo1988ali** [rebelonion/Dantotsu#475]
Date/time: Sat Sep 07 23:28:01 GMT+01:00 2024
Device: NX729J
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: nubia
Brand: nubia
Product: NX729J-UN
Device: NX729J-UN
Hardware: qcom
Host: scl-shr01-ironic02
ID: UKQ1.230917.001
Type: user
User: zte
Tags: release-keys
Time: 1723002856000
Radio: MPSS.DE.3.0-02351-KAILUA_GEN_PACK-1.24317.39.40606.10
Bootloader: unknown
Board: kalama
Fingerprint: nubia/NX729J-UN/NX729J-UN:14/UKQ1.230917.001/20240807.115337:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: pool-11-thread-2
Activity: ExoplayerView
Exception: Player is accessed on the wrong thread.
Current thread: 'pool-11-thread-2'
Expected thread: 'main'
See https://developer.android.com/guide/topics/media/issues/player-accessed-on-wrong-thread
Stack trace:
java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'pool-11-thread-2'
Expected thread: 'main'
See https://developer.android.com/guide/topics/media/issues/player-accessed-on-wrong-thread
	at androidx.media3.exoplayer.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2860)
	at androidx.media3.exoplayer.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:825)
	at androidx.media3.common.BasePlayer.pause(BasePlayer.java:119)
	at ani.dantotsu.media.anime.ExoplayerView.onCreate$lambda$4(ExoplayerView.kt:481)
	at ani.dantotsu.media.anime.ExoplayerView.$r8$lambda$Eq9NRbAr46zXneOTwjLb-UEOkKI(Unknown Source:0)
	at ani.dantotsu.media.anime.ExoplayerView$$ExternalSyntheticLambda21.onAudioFocusChange(D8$$SyntheticClass:0)
	at android.media.AudioManager$ServiceEventHandlerDelegate$RunnableTask.run(AudioManager.java:4521)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by rebelonion** [comment]
Hopefully better in 3.2.0+
