### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EricLSSR** [rebelonion/Dantotsu#487]
Date/time: Mon Sep 30 23:44:11 GMT-03:00 2024
Device: SM-A156M
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: samsung
Brand: samsung
Product: a15xub
Device: a15x
Hardware: mt6835
Host: 21DKG915
ID: UP1A.231005.007
Type: user
User: dpi
Tags: release-keys
Time: 1725296649000
Radio: A156MUBU3BXG7,A156MUBU3BXG7
Bootloader: A156MUBS3BXI1
Board: a15x
Fingerprint: samsung/a15xub/a15x:14/UP1A.231005.007/A156MUBS3BXI1:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: DefaultDispatcher-worker-2
Activity: ExoplayerView
Exception: FFmpegKit failed to start on brand: samsung, model: SM-A156M, device: a15x, api level: 34, abis: arm64-v8a armeabi-v7a armeabi, 32bit abis: armeabi-v7a armeabi, 64bit abis: arm64-v8a.
Stack trace:
java.lang.Error: FFmpegKit failed to start on brand: samsung, model: SM-A156M, device: a15x, api level: 34, abis: arm64-v8a armeabi-v7a armeabi, 32bit abis: armeabi-v7a armeabi, 64bit abis: arm64-v8a.
	at com.arthenica.ffmpegkit.NativeLoader.loadLibrary(NativeLoader.java:50)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKitAbiDetect(NativeLoader.java:130)
	at com.arthenica.ffmpegkit.AbiDetect.<clinit>(AbiDetect.java:30)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	at ani.dantotsu.downloadAddon.DownloadAddon.setDownloadPath(DownloadAddon.kt:25)
	at ani.dantotsu.download.anime.AnimeDownloaderService$download$2.invokeSuspend(AnimeDownloaderService.kt:237)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e51df70, Dispatchers.Default]
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~gx132jmeESrHAHD4mfOYVQ==/dantotsu.downloadAddon-8A3leK8weEEiTn7-FFnt4Q==/lib/arm/libffmpegkit_abidetect.so" is 32-bit instead of 64-bit
	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1765)
	at com.arthenica.ffmpegkit.NativeLoader.loadLibrary(NativeLoader.java:48)
	... 17 more

**Comment by rebelonion** [comment]
lmk if it happens a lot
