### ISSUE TITLE
App Died - Crash report

### ISSUE THREAD

**Issue by Z3U5404** [rebelonion/Dantotsu#488]
Date/time: Tue Oct 01 14:37:32 GMT+05:30 2024
Device: SM-M135FU
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: samsung
Brand: samsung
Product: m13ins
Device: m13
Hardware: exynos850
Host: 21DK7906
ID: UP1A.231005.007
Type: user
User: dpi
Tags: release-keys
Time: 1719381468000
Radio: M135FUXXU6EXE6,M135FUXXU6EXE6
Bootloader: M135FUXXU6EXF3
Board: exynos850
Fingerprint: samsung/m13ins/m13:14/UP1A.231005.007/M135FUXXU6EXF3:user/release-keys
Supported ABIs: armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: 
Is emulator: false
--------------------------------
Thread: main
Activity: MediaDetailsActivity
Exception: Unable to resume activity {ani.dantotsu/ani.dantotsu.media.MediaDetailsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
Stack trace:
java.lang.RuntimeException: Unable to resume activity {ani.dantotsu/ani.dantotsu.media.MediaDetailsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5427)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
	at ani.dantotsu.media.MediaDetailsActivity.getNavBar(MediaDetailsActivity.kt:76)
	at ani.dantotsu.media.MediaDetailsActivity.onResume(MediaDetailsActivity.kt:427)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	... 13 more

**Comment by rebelonion** [comment]
closing as duplicate
