### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by ah13d** [rebelonion/Dantotsu#491]
Date/time: Sat Oct 05 20:58:13 GMT+03:00 2024
Device: Redmi Note 4
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: Xiaomi
Brand: Xiaomi
Product: lineage_mido
Device: mido
Hardware: qcom
Host: android-build
ID: AP2A.240905.003
Type: user
User: nobody
Tags: release-keys
Time: 1726678857000
Radio: .2.c1-00442-8953_GEN_PACK-1.148143.1.163979.1,.2.c1-00442-8953_GEN_PACK-1.148143.1.163979.1
Bootloader: unknown
Board: MSM8953
Fingerprint: xiaomi/mido/mido:7.0/NRD90M/V9.6.1.0.NCFMIFD:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: main
Activity: MediaDetailsActivity
Exception: Unable to resume activity {ani.dantotsu/ani.dantotsu.media.MediaDetailsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
Stack trace:
java.lang.RuntimeException: Unable to resume activity {ani.dantotsu/ani.dantotsu.media.MediaDetailsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5251)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5284)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
	at ani.dantotsu.media.MediaDetailsActivity.getNavBar(MediaDetailsActivity.kt:76)
	at ani.dantotsu.media.MediaDetailsActivity.onResume(MediaDetailsActivity.kt:427)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1726)
	at android.app.Activity.performResume(Activity.java:9118)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5241)
	... 14 more

**Comment by rebelonion** [comment]
closing as duplicate
