### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by NIYAAZ53** [rebelonion/Dantotsu#512]
Date/time: Wed Nov 06 23:25:15 GMT+02:00 2024
Device: SM-A528B
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: samsung
Brand: samsung
Product: a52sxqxx
Device: a52sxq
Hardware: qcom
Host: VPDJR108
ID: UP1A.231005.007
Type: user
User: dpi
Tags: release-keys
Time: 1700708755000
Radio: A528BXXU5FWK8
Bootloader: A528BXXU5FWK8
Board: lahaina
Fingerprint: samsung/a52sxqxx/a52sxq:14/UP1A.231005.007/A528BXXU5FWK8:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: main
Activity: MediaDetailsActivity
Exception: Unable to resume activity {ani.dantotsu/ani.dantotsu.media.MediaDetailsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
Stack trace:
java.lang.RuntimeException: Unable to resume activity {ani.dantotsu/ani.dantotsu.media.MediaDetailsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5426)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5507)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property navBar has not been initialized
	at ani.dantotsu.media.MediaDetailsActivity.getNavBar(MediaDetailsActivity.kt:76)
	at ani.dantotsu.media.MediaDetailsActivity.onResume(MediaDetailsActivity.kt:427)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9103)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	... 13 more

**Comment by rebelonion** [comment]
closing as duplicate
