### ISSUE TITLE
Some error in animepahe

### ISSUE THREAD

**Issue by Aeropro4** [rebelonion/Dantotsu#53]
This error comes when selecting server tho thr video still runs, but then also pls take a look:
java.lang.Exception: Unknown video format
	at ani.dantotsu.parsers.VideoServerPassthrough.AniVideoToSaiVideo(AniyomiAdapter.kt:515)
	at ani.dantotsu.parsers.VideoServerPassthrough.extract(AniyomiAdapter.kt:475)
	at ani.dantotsu.parsers.VideoExtractor.load$suspendImpl(VideoExtractor.kt:29)
	at ani.dantotsu.parsers.VideoExtractor.load(Unknown Source:0)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2$1$1$1.invokeSuspend(AnimeParser.kt:106)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2$1$1$1.invoke(Unknown Source:8)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2$1$1$1.invoke(Unknown Source:2)
	at ani.dantotsu.NetworkKt.tryWithSuspend(Network.kt:127)
	at ani.dantotsu.NetworkKt.tryWithSuspend$default(Network.kt:125)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2$1.invokeSuspend(AnimeParser.kt:105)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2$1.invoke(Unknown Source:8)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2$1.invoke(Unknown Source:4)
	at ani.dantotsu.NetworkKt$asyncMap$1$1$1.invokeSuspend(Network.kt:95)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at ani.dantotsu.NetworkKt.asyncMap(Network.kt:94)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2.invokeSuspend(AnimeParser.kt:103)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2.invoke(Unknown Source:8)
	at ani.dantotsu.parsers.AnimeParser$loadByVideoServers$2.invoke(Unknown Source:2)
	at ani.dantotsu.NetworkKt.tryWithSuspend(Network.kt:127)
	at ani.dantotsu.NetworkKt.tryWithSuspend$default(Network.kt:125)
	at ani.dantotsu.parsers.AnimeParser.loadByVideoServers$suspendImpl(AnimeParser.kt:102)
	at ani.dantotsu.parsers.AnimeParser.loadByVideoServers(Unknown Source:0)
	at ani.dantotsu.media.MediaDetailsViewModel.loadEpisodeVideos(MediaDetailsViewModel.kt:152)
	at ani.dantotsu.media.MediaDetailsViewModel.loadEpisodeVideos$default(MediaDetailsViewModel.kt:144)
	at ani.dantotsu.media.anime.SelectorDialogFragment$onViewCreated$1$8.invokeSuspend(SelectorDialogFragment.kt:147)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by rebelonion** [comment]
how did you obtain this stack trace?
is it a custom build?

**Comment by Aeropro4** [comment]
> how did you obtain this stack trace?
> is it a custom build?

Nah the previous saikou creator told that if u long tap the error message then u can copy the error

**Comment by rebelonion** [comment]
Is this the beta version or the stable?
Also could you provide a source and server that causes this?

**Comment by Aeropro4** [comment]
> Is this the beta version or the stable?
It's beta tho it happened in the latest stable aswell
> Also could you provide a source and server that causes this? 
Source: animepahe 
And it's during server selection tab not for a specific one
And this error comes like randomly so that's hard to capture

**Comment by rebelonion** [comment]
should be fixed
If not I'll reopen
