### ISSUE TITLE
Crashing when resuming novels on galaxy s23

### ISSUE THREAD

**Issue by Marce2148** [rebelonion/Dantotsu#538]
### Steps to Reproduce

Navigate to Manga section
Scroll to novels
Open any novel and scroll a few pages
Close novel
Reopen

### Expected Outcome

The application should continue the novel on the page you left off. 

### Actual Outcome

The app crashed and displayed an error message.

### Error Logs (if applicable)

Date/time: Tue Dec 03 14:23:06 CST 2024
Device: SM-S911U1
OS version: 14
App version: 3.1.0
App version code: 300100000
SDK version: 34
Manufacturer: samsung
Brand: samsung
Product: dm1quew
Device: dm1q
Hardware: qcom
Host: SWDK3909
ID: UP1A.231005.007
Type: user
User: dpi
Tags: release-keys
Time: 1721615952000
Radio: S911U1UES4CXG8,S911U1UES4CXG8
Bootloader: S911U1UES4CXG8
Board: kalama
Fingerprint: samsung/dm1quew/dm1q:14/UP1A.231005.007/S911U1UES4CXG8:user/release-keys
Supported ABIs: arm64-v8a, armeabi-v7a, armeabi
Supported 32 bit ABIs: armeabi-v7a, armeabi
Supported 64 bit ABIs: arm64-v8a
Is emulator: false
--------------------------------
Thread: main
Activity: NovelReaderActivity
Exception: Unexpected JSON token at offset 42: Failed to parse type 'double' for input 'null' at path: $.fraction
JSON input: {"cfi":"epubcfi(/6/18!/4)","fraction":null,"tocItem":{"label":"Prologue","href":"OEBPS/Text/part0007.xhtml","subitems":null,"id":3},"currentLocation":null,"nextLocation":null,"totalLocations":217}
Stack trace:
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 42: Failed to parse type 'double' for input 'null' at path: $.fraction
JSON input: {"cfi":"epubcfi(/6/18!/4)","fraction":null,"tocItem":{"label":"Prologue","href":"OEBPS/Text/part0007.xhtml","subitems":null,"id":3},"currentLocation":null,"nextLocation":null,"totalLocations":217}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeDouble(StreamingJsonDecoder.kt:424)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeDoubleElement(AbstractDecoder.kt:56)
	at com.vipulog.ebookreader.RelocationInfo$$serializer.deserialize(RelocationInfo.kt:5)
	at com.vipulog.ebookreader.RelocationInfo$$serializer.deserialize(RelocationInfo.kt:5)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at com.vipulog.ebookreader.EbookReaderView$JavaScriptInterface$onRelocated$1.invokeSuspend(EbookReaderView.kt:248)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5b4a871, Dispatchers.Main]

### Dartotsu Version

3.1.0

### Operating System Version

Android 14

### Device Information

Samsung galaxy s23

### Submission Checklist

- [X] I have searched existing issues to confirm this is not a duplicate.
- [X] I have provided a clear and descriptive title.
- [X] I am using the **[latest](https://github.com/rebelonion/Dantotsu/latest)** version of Dantotsu. If not, I have provided a reason for not updating.
- [X] I have updated all relevant extensions or dependencies.
- [X] I have filled out all the requested information accurately.

**Comment by Marce2148** [comment]
It isn't a Manga it is the libgen extension with the novel no game no life.

**Comment by SamSupernoods** [comment]
is it only no game no life or is there more

**Comment by Marce2148** [comment]
All of the novels crash when I resume them. I've tried multiple sources
from the downloads list.

**Comment by SamSupernoods** [comment]
i recommend u go into the discord sever and make a bug report as more people see discord

**Comment by Marce2148** [comment]
Thanks, I'll do that as soon as possible.

**Comment by VipulOG** [comment]
Fixed in #536. Please test with the latest pretest version from Discord and let me know if it persists.
